### ISSUE TITLE
封装的很详细

### ISSUE THREAD

**Issue by kuaige** [limedroid/XDroid#1]
希望有个demo那就更好了.

**Comment by limedroid** [comment]
demo正在努力准备中，预计这个周末可以出来 @kuaige

**Comment by kuaige** [comment]
恩恩,辛苦了.

**Comment by bengben** [comment]
期待。。。。

**Comment by limedroid** [comment]
Demo已上传 @kuaige @bengben

**Comment by kuaige** [comment]
@limedroid  demo 打开闪退,
java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

**Comment by kuaige** [comment]
@limedroid  问题还是很多,主题这个解决了,还有EvenBus有问题好像要添加注解方法,

**Comment by limedroid** [comment]
eventbus 使用的是3.0 需要使用注解 ,Demo还需要完整的测试下，预计明日可完成 @kuaige
