### ISSUE TITLE
ButterKnife unbind

### ISSUE THREAD

**Issue by Sum41forever** [limedroid/XDroid#3]
最近打算用这个框架写新项目。
看了下，基类里面有解绑的，但是没有用

依赖库里KnifeKit工具类里面有 静态方法解绑。
但是没有用到啊，可以加到基类里。

**Comment by Sum41forever** [comment]
封装的很不错 EventBus不会用。。尴尬

**Comment by limedroid** [comment]
解绑我不建议用，会产生一些问题。刚开始我是加上了，后面去掉了。  @Sum41forever
