### ISSUE TITLE
AndroidStudio2.2.2无法集成的问题

### ISSUE THREAD

**Issue by ZhangLanqiu** [limedroid/XDroid#4]
按照您的步骤进行集成，没有成功！ libray是直接复制粘贴到项目中吗？？？？ 能不能直接发布 jcenter ,直接依赖？

**Comment by limedroid** [comment]
不是复制粘贴，是直接import module，目前没有计划发布到jcenter，希望您可以加入XDroid交流群153569290   @ZhangLanqiu
