### ISSUE TITLE
eventBus 写的有问题

### ISSUE THREAD

**Issue by zhjun2016** [limedroid/XDroid#5]
使用你的框架，如果使用eventBus，按您教程，集成的基类，订阅方将方法useEventBus 返回true, 发送方BusFactory.getBus.register ，或者post，订阅方没有接受到消息。请问订阅方类，怎么订阅，按evnetBus3.0方法，自定义方法头上写@Subscribe，不生效。大神能写一个demo说明，你怎么使用你的BusFactory吗？

**Comment by limedroid** [comment]
建议你看下eventbus的相关用法，xdroid对eventbus没有特别封装。@zhjun2016
