### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by qiaoyhh** [limedroid/XDroid#7]
VDelegateBase  VDelegate这两个类主要作用是做什么的呀，，如果抽取您的框架，不加这俩个类会怎么样呀

**Comment by limedroid** [comment]
这两个主要用作页面的统一操作，减少基类Activity代码量，比如说 广告统计等。不加也是可以的 。 @qiaoyhh

**Comment by qiaoyhh** [comment]
好的，谢谢！

**Comment by qiaoyhh** [comment]
经常会出这个 v can not be null 问题

**Comment by qiaoyhh** [comment]
@limedroid
